### ISSUE TITLE
when I use the SHA  76a9d8e333f081a9df30b5f8706e9be81517665c  to compile femu,It produces the error outside array bounds.

### ISSUE THREAD

**Issue by HugeOrhuge** [MoatSysLab/FEMU#136]
On Ubuntu 22.04.4 LTS
the error image:

what can I do to solve this problem?
thanks.

**Comment by HugeOrhuge** [comment]
![1](https://github.com/MoatSysLab/FEMU/assets/117280571/bd9555e3-037d-4b8f-89c8-ff4fac3fe183)

**Comment by huaicheng** [comment]
You should be able to bypass the above errors by adding ``--disable-werror`` to the ``./configure`` cmd in ``femu-compile.sh``.

**Comment by HugeOrhuge** [comment]
> You should be able to bypass the above errors by adding `--disable-werror` to the `./configure` cmd in `femu-compile.sh`.

it works,thanks!
